services:
  lemonade-app:
    build: .
    container_name: lemonade-app
    ports:
      - "8001:8001"
    # volumes:  ← REMOVA ESTA LINHA
    #   - lemonade-data:/root/.lemonade
    stdin_open: true
    tty: true
    command: >
      bash -c "
        lemonade-server-dev serve --port 8001 &
        sleep 5 &&
        cd /app/file-assistant &&
        tiny-agents run agent.docker.json
      "

# Sem seção volumes
