# A diretiva 'version' é obsoleta e removida para seguir as boas práticas.
services:
  # Serviço para o Lemonade Server
  lemonade-server:
    build: .
    container_name: lemonade-server
    # O comando agora é mais simples e usa a porta 8001.
    command: ["lemonade-server-dev", "serve", "--port", "8001"]
    ports:
      # Mapeia a porta 8001 do contêiner para a porta 8001 da sua máquina.
      - "8001:8001"
    volumes:
      # O volume ainda é útil para persistir quaisquer outros modelos ou logs.
      - lemonade-data:/root/.lemonade

  # Serviço para o Agente Interativo
  agent:
    build: .
    container_name: agent
    working_dir: /app/file-assistant
    # O comando do agente agora é mais simples, sem dependência de entrypoint.
    command: ["tiny-agents", "run", "agent.docker.json"]
    depends_on:
      # O agente ainda espera o servidor iniciar.
      - lemonade-server
    stdin_open: true
    tty: true

# Declara o volume nomeado para persistência dos dados.
volumes:
  lemonade-data: