# --- Configurações Principais do Site ---
title: AI HR Talent Analyzer
description: Documentação completa para o AI HR Talent Analyzer, uma ferramenta de RH para análise de vagas e currículos com LLMs locais.
baseurl: "/ai-hr-talent-analyzer" # O subdiretório do seu site, e.g. /blog
url: "https://Jcnok.github.io" # O domínio base do seu site

# --- Tema e Plugins ---
# O tema minima é um bom ponto de partida, mas os nossos estilos em assets/css/style.css irão sobrescrevê-lo.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# --- Build settings ---
markdown: kramdown
highlighter: rouge

# --- Informações do Autor e Social ---
author:
  name: Julio Okuda
  email: julio.okuda@gmail.com

social_links:
  github: Jcnok/ai-hr-talent-analyzer

# A navegação foi movida para o arquivo _layouts/default.html para maior controle.
# A seção 'header_pages' não é mais necessária aqui.

# Excluir arquivos do build final
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/