# Fluxo de trabalho para construir e implantar um site Jekyll no GitHub Pages
name: Deploy Jekyll Site to Pages

on:
  # Executa quando há um push para a branch `main`
  push:
    branches: ["main"]

  # Permite que você execute este fluxo de trabalho manualmente na aba Actions
  workflow_dispatch:

# Define as permissões necessárias para o job de implantação
permissions:
  contents: read
  pages: write
  id-token: write

# Permite apenas uma implantação concorrente, cancelando execuções mais antigas
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Job de construção
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Versão recomendada para o Jekyll atual
          bundler-cache: true # Armazena em cache as gems para builds mais rápidos
          working-directory: './docs' # Especifica que o Gemfile está em /docs
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4
      - name: Build with Jekyll
        # Executa o build do Jekyll, especificando os diretórios de origem e destino
        run: bundle exec jekyll build --source ./docs --destination ./_site
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        # Faz o upload do site construído como um artefato para o job de implantação
        uses: actions/upload-pages-artifact@v3

  # Job de implantação
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4